
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.4'
          otp-version: '24'
      - run: mix deps.get --only
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
