name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.4'
          otp-version: '24'
      - run: mix deps.get --only
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.4'
          otp-version: '24'
      - id: plt-cache
        uses: actions/cache@v3
        with:
          path: _build/${{env.MIX_ENV}}/dialyxir_*
          key: plt-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}
          restore-keys: plt-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}
      - run: mix deps.get --only
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt --format github
      - run: mix dialyzer --format github
